
-- Generated Mock Data
SET FOREIGN_KEY_CHECKS=0;

-- 1. Exams
INSERT INTO qb_exams (title, exam_type, description, created_at) VALUES 
('Full Mock Exam - Standard', 'IELTS', 'A standard mock exam placeholder.', NOW()),
('Real Exam - Official', 'REAL_EXAM', 'A real exam placeholder.', NOW());
SET @mock_exam = LAST_INSERT_ID();
SET @real_exam = @mock_exam + 1;


-- LISTENING Part 1 for Mock Test
INSERT INTO qb_question_groups (skill, title, content, difficulty_band, author_id, created_at) VALUES ('LISTENING', 'Mock Test - LISTENING Part 1', 'Placeholder audio transcript for LISTENING part 1...', 'BAND_5_6', 5, NOW());
SET @group_1 = LAST_INSERT_ID();
INSERT INTO qb_exam_groups (exam_id, group_id) VALUES (@mock_exam, @group_1);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q1: Answer this MULTIPLE_CHOICE question for LISTENING Part 1.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_1);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'FILL_BLANK', 'BAND_5_6', 'Q2: Answer this FILL_BLANK question for LISTENING Part 1.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_1);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MATCHING', 'BAND_5_6', 'Q3: Answer this MATCHING question for LISTENING Part 1.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_1);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q4: Answer this MULTIPLE_CHOICE question for LISTENING Part 1.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_1);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'FILL_BLANK', 'BAND_5_6', 'Q5: Answer this FILL_BLANK question for LISTENING Part 1.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_1);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MATCHING', 'BAND_5_6', 'Q6: Answer this MATCHING question for LISTENING Part 1.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_1);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q7: Answer this MULTIPLE_CHOICE question for LISTENING Part 1.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_1);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'FILL_BLANK', 'BAND_5_6', 'Q8: Answer this FILL_BLANK question for LISTENING Part 1.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_1);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MATCHING', 'BAND_5_6', 'Q9: Answer this MATCHING question for LISTENING Part 1.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_1);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q10: Answer this MULTIPLE_CHOICE question for LISTENING Part 1.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_1);

-- LISTENING Part 2 for Mock Test
INSERT INTO qb_question_groups (skill, title, content, difficulty_band, author_id, created_at) VALUES ('LISTENING', 'Mock Test - LISTENING Part 2', 'Placeholder audio transcript for LISTENING part 2...', 'BAND_5_6', 5, NOW());
SET @group_2 = LAST_INSERT_ID();
INSERT INTO qb_exam_groups (exam_id, group_id) VALUES (@mock_exam, @group_2);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q1: Answer this MULTIPLE_CHOICE question for LISTENING Part 2.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_2);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'FILL_BLANK', 'BAND_5_6', 'Q2: Answer this FILL_BLANK question for LISTENING Part 2.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_2);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MATCHING', 'BAND_5_6', 'Q3: Answer this MATCHING question for LISTENING Part 2.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_2);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q4: Answer this MULTIPLE_CHOICE question for LISTENING Part 2.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_2);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'FILL_BLANK', 'BAND_5_6', 'Q5: Answer this FILL_BLANK question for LISTENING Part 2.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_2);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MATCHING', 'BAND_5_6', 'Q6: Answer this MATCHING question for LISTENING Part 2.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_2);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q7: Answer this MULTIPLE_CHOICE question for LISTENING Part 2.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_2);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'FILL_BLANK', 'BAND_5_6', 'Q8: Answer this FILL_BLANK question for LISTENING Part 2.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_2);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MATCHING', 'BAND_5_6', 'Q9: Answer this MATCHING question for LISTENING Part 2.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_2);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q10: Answer this MULTIPLE_CHOICE question for LISTENING Part 2.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_2);

-- LISTENING Part 3 for Mock Test
INSERT INTO qb_question_groups (skill, title, content, difficulty_band, author_id, created_at) VALUES ('LISTENING', 'Mock Test - LISTENING Part 3', 'Placeholder audio transcript for LISTENING part 3...', 'BAND_5_6', 5, NOW());
SET @group_3 = LAST_INSERT_ID();
INSERT INTO qb_exam_groups (exam_id, group_id) VALUES (@mock_exam, @group_3);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q1: Answer this MULTIPLE_CHOICE question for LISTENING Part 3.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_3);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'FILL_BLANK', 'BAND_5_6', 'Q2: Answer this FILL_BLANK question for LISTENING Part 3.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_3);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MATCHING', 'BAND_5_6', 'Q3: Answer this MATCHING question for LISTENING Part 3.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_3);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q4: Answer this MULTIPLE_CHOICE question for LISTENING Part 3.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_3);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'FILL_BLANK', 'BAND_5_6', 'Q5: Answer this FILL_BLANK question for LISTENING Part 3.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_3);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MATCHING', 'BAND_5_6', 'Q6: Answer this MATCHING question for LISTENING Part 3.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_3);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q7: Answer this MULTIPLE_CHOICE question for LISTENING Part 3.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_3);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'FILL_BLANK', 'BAND_5_6', 'Q8: Answer this FILL_BLANK question for LISTENING Part 3.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_3);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MATCHING', 'BAND_5_6', 'Q9: Answer this MATCHING question for LISTENING Part 3.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_3);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q10: Answer this MULTIPLE_CHOICE question for LISTENING Part 3.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_3);

-- LISTENING Part 4 for Mock Test
INSERT INTO qb_question_groups (skill, title, content, difficulty_band, author_id, created_at) VALUES ('LISTENING', 'Mock Test - LISTENING Part 4', 'Placeholder audio transcript for LISTENING part 4...', 'BAND_5_6', 5, NOW());
SET @group_4 = LAST_INSERT_ID();
INSERT INTO qb_exam_groups (exam_id, group_id) VALUES (@mock_exam, @group_4);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q1: Answer this MULTIPLE_CHOICE question for LISTENING Part 4.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_4);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'FILL_BLANK', 'BAND_5_6', 'Q2: Answer this FILL_BLANK question for LISTENING Part 4.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_4);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MATCHING', 'BAND_5_6', 'Q3: Answer this MATCHING question for LISTENING Part 4.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_4);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q4: Answer this MULTIPLE_CHOICE question for LISTENING Part 4.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_4);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'FILL_BLANK', 'BAND_5_6', 'Q5: Answer this FILL_BLANK question for LISTENING Part 4.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_4);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MATCHING', 'BAND_5_6', 'Q6: Answer this MATCHING question for LISTENING Part 4.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_4);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q7: Answer this MULTIPLE_CHOICE question for LISTENING Part 4.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_4);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'FILL_BLANK', 'BAND_5_6', 'Q8: Answer this FILL_BLANK question for LISTENING Part 4.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_4);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MATCHING', 'BAND_5_6', 'Q9: Answer this MATCHING question for LISTENING Part 4.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_4);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q10: Answer this MULTIPLE_CHOICE question for LISTENING Part 4.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_4);

-- READING Part 1 for Mock Test
INSERT INTO qb_question_groups (skill, title, content, difficulty_band, author_id, created_at) VALUES ('READING', 'Mock Test - READING Part 1', 'Placeholder content for READING passage 1...', 'BAND_5_6', 5, NOW());
SET @group_5 = LAST_INSERT_ID();
INSERT INTO qb_exam_groups (exam_id, group_id) VALUES (@mock_exam, @group_5);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q1: Answer this MULTIPLE_CHOICE question for READING Part 1.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_5);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'FILL_BLANK', 'BAND_5_6', 'Q2: Answer this FILL_BLANK question for READING Part 1.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_5);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MATCHING', 'BAND_5_6', 'Q3: Answer this MATCHING question for READING Part 1.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_5);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q4: Answer this MULTIPLE_CHOICE question for READING Part 1.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_5);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'FILL_BLANK', 'BAND_5_6', 'Q5: Answer this FILL_BLANK question for READING Part 1.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_5);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MATCHING', 'BAND_5_6', 'Q6: Answer this MATCHING question for READING Part 1.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_5);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q7: Answer this MULTIPLE_CHOICE question for READING Part 1.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_5);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'FILL_BLANK', 'BAND_5_6', 'Q8: Answer this FILL_BLANK question for READING Part 1.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_5);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MATCHING', 'BAND_5_6', 'Q9: Answer this MATCHING question for READING Part 1.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_5);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q10: Answer this MULTIPLE_CHOICE question for READING Part 1.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_5);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'FILL_BLANK', 'BAND_5_6', 'Q11: Answer this FILL_BLANK question for READING Part 1.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_5);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MATCHING', 'BAND_5_6', 'Q12: Answer this MATCHING question for READING Part 1.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_5);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q13: Answer this MULTIPLE_CHOICE question for READING Part 1.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_5);

-- READING Part 2 for Mock Test
INSERT INTO qb_question_groups (skill, title, content, difficulty_band, author_id, created_at) VALUES ('READING', 'Mock Test - READING Part 2', 'Placeholder content for READING passage 2...', 'BAND_5_6', 5, NOW());
SET @group_6 = LAST_INSERT_ID();
INSERT INTO qb_exam_groups (exam_id, group_id) VALUES (@mock_exam, @group_6);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q1: Answer this MULTIPLE_CHOICE question for READING Part 2.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_6);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'FILL_BLANK', 'BAND_5_6', 'Q2: Answer this FILL_BLANK question for READING Part 2.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_6);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MATCHING', 'BAND_5_6', 'Q3: Answer this MATCHING question for READING Part 2.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_6);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q4: Answer this MULTIPLE_CHOICE question for READING Part 2.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_6);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'FILL_BLANK', 'BAND_5_6', 'Q5: Answer this FILL_BLANK question for READING Part 2.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_6);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MATCHING', 'BAND_5_6', 'Q6: Answer this MATCHING question for READING Part 2.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_6);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q7: Answer this MULTIPLE_CHOICE question for READING Part 2.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_6);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'FILL_BLANK', 'BAND_5_6', 'Q8: Answer this FILL_BLANK question for READING Part 2.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_6);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MATCHING', 'BAND_5_6', 'Q9: Answer this MATCHING question for READING Part 2.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_6);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q10: Answer this MULTIPLE_CHOICE question for READING Part 2.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_6);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'FILL_BLANK', 'BAND_5_6', 'Q11: Answer this FILL_BLANK question for READING Part 2.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_6);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MATCHING', 'BAND_5_6', 'Q12: Answer this MATCHING question for READING Part 2.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_6);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q13: Answer this MULTIPLE_CHOICE question for READING Part 2.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_6);

-- READING Part 3 for Mock Test
INSERT INTO qb_question_groups (skill, title, content, difficulty_band, author_id, created_at) VALUES ('READING', 'Mock Test - READING Part 3', 'Placeholder content for READING passage 3...', 'BAND_5_6', 5, NOW());
SET @group_7 = LAST_INSERT_ID();
INSERT INTO qb_exam_groups (exam_id, group_id) VALUES (@mock_exam, @group_7);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q1: Answer this MULTIPLE_CHOICE question for READING Part 3.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_7);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'FILL_BLANK', 'BAND_5_6', 'Q2: Answer this FILL_BLANK question for READING Part 3.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_7);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MATCHING', 'BAND_5_6', 'Q3: Answer this MATCHING question for READING Part 3.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_7);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q4: Answer this MULTIPLE_CHOICE question for READING Part 3.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_7);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'FILL_BLANK', 'BAND_5_6', 'Q5: Answer this FILL_BLANK question for READING Part 3.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_7);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MATCHING', 'BAND_5_6', 'Q6: Answer this MATCHING question for READING Part 3.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_7);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q7: Answer this MULTIPLE_CHOICE question for READING Part 3.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_7);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'FILL_BLANK', 'BAND_5_6', 'Q8: Answer this FILL_BLANK question for READING Part 3.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_7);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MATCHING', 'BAND_5_6', 'Q9: Answer this MATCHING question for READING Part 3.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_7);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q10: Answer this MULTIPLE_CHOICE question for READING Part 3.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_7);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'FILL_BLANK', 'BAND_5_6', 'Q11: Answer this FILL_BLANK question for READING Part 3.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_7);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MATCHING', 'BAND_5_6', 'Q12: Answer this MATCHING question for READING Part 3.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_7);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q13: Answer this MULTIPLE_CHOICE question for READING Part 3.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_7);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'FILL_BLANK', 'BAND_5_6', 'Q14: Answer this FILL_BLANK question for READING Part 3.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_7);

-- Writing Tasks for Mock Test
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id) VALUES ('WRITING', 'ESSAY', 'BAND_5_6', 'Writing Task 1 for Mock Test: Discuss...', '{}', false, 5);
SET @writing_MockTest_1 = LAST_INSERT_ID();
INSERT INTO qb_exam_questions (exam_id, question_id) VALUES (@mock_exam, @writing_MockTest_1);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id) VALUES ('WRITING', 'ESSAY', 'BAND_5_6', 'Writing Task 2 for Mock Test: Discuss...', '{}', false, 5);
SET @writing_MockTest_2 = LAST_INSERT_ID();
INSERT INTO qb_exam_questions (exam_id, question_id) VALUES (@mock_exam, @writing_MockTest_2);

-- LISTENING Part 1 for Real Test
INSERT INTO qb_question_groups (skill, title, content, difficulty_band, author_id, created_at) VALUES ('LISTENING', 'Real Test - LISTENING Part 1', 'Placeholder audio transcript for LISTENING part 1...', 'BAND_5_6', 5, NOW());
SET @group_8 = LAST_INSERT_ID();
INSERT INTO qb_exam_groups (exam_id, group_id) VALUES (@real_exam, @group_8);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q1: Answer this MULTIPLE_CHOICE question for LISTENING Part 1.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_8);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'FILL_BLANK', 'BAND_5_6', 'Q2: Answer this FILL_BLANK question for LISTENING Part 1.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_8);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MATCHING', 'BAND_5_6', 'Q3: Answer this MATCHING question for LISTENING Part 1.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_8);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q4: Answer this MULTIPLE_CHOICE question for LISTENING Part 1.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_8);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'FILL_BLANK', 'BAND_5_6', 'Q5: Answer this FILL_BLANK question for LISTENING Part 1.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_8);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MATCHING', 'BAND_5_6', 'Q6: Answer this MATCHING question for LISTENING Part 1.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_8);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q7: Answer this MULTIPLE_CHOICE question for LISTENING Part 1.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_8);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'FILL_BLANK', 'BAND_5_6', 'Q8: Answer this FILL_BLANK question for LISTENING Part 1.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_8);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MATCHING', 'BAND_5_6', 'Q9: Answer this MATCHING question for LISTENING Part 1.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_8);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q10: Answer this MULTIPLE_CHOICE question for LISTENING Part 1.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_8);

-- LISTENING Part 2 for Real Test
INSERT INTO qb_question_groups (skill, title, content, difficulty_band, author_id, created_at) VALUES ('LISTENING', 'Real Test - LISTENING Part 2', 'Placeholder audio transcript for LISTENING part 2...', 'BAND_5_6', 5, NOW());
SET @group_9 = LAST_INSERT_ID();
INSERT INTO qb_exam_groups (exam_id, group_id) VALUES (@real_exam, @group_9);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q1: Answer this MULTIPLE_CHOICE question for LISTENING Part 2.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_9);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'FILL_BLANK', 'BAND_5_6', 'Q2: Answer this FILL_BLANK question for LISTENING Part 2.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_9);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MATCHING', 'BAND_5_6', 'Q3: Answer this MATCHING question for LISTENING Part 2.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_9);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q4: Answer this MULTIPLE_CHOICE question for LISTENING Part 2.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_9);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'FILL_BLANK', 'BAND_5_6', 'Q5: Answer this FILL_BLANK question for LISTENING Part 2.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_9);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MATCHING', 'BAND_5_6', 'Q6: Answer this MATCHING question for LISTENING Part 2.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_9);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q7: Answer this MULTIPLE_CHOICE question for LISTENING Part 2.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_9);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'FILL_BLANK', 'BAND_5_6', 'Q8: Answer this FILL_BLANK question for LISTENING Part 2.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_9);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MATCHING', 'BAND_5_6', 'Q9: Answer this MATCHING question for LISTENING Part 2.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_9);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q10: Answer this MULTIPLE_CHOICE question for LISTENING Part 2.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_9);

-- LISTENING Part 3 for Real Test
INSERT INTO qb_question_groups (skill, title, content, difficulty_band, author_id, created_at) VALUES ('LISTENING', 'Real Test - LISTENING Part 3', 'Placeholder audio transcript for LISTENING part 3...', 'BAND_5_6', 5, NOW());
SET @group_10 = LAST_INSERT_ID();
INSERT INTO qb_exam_groups (exam_id, group_id) VALUES (@real_exam, @group_10);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q1: Answer this MULTIPLE_CHOICE question for LISTENING Part 3.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_10);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'FILL_BLANK', 'BAND_5_6', 'Q2: Answer this FILL_BLANK question for LISTENING Part 3.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_10);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MATCHING', 'BAND_5_6', 'Q3: Answer this MATCHING question for LISTENING Part 3.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_10);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q4: Answer this MULTIPLE_CHOICE question for LISTENING Part 3.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_10);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'FILL_BLANK', 'BAND_5_6', 'Q5: Answer this FILL_BLANK question for LISTENING Part 3.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_10);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MATCHING', 'BAND_5_6', 'Q6: Answer this MATCHING question for LISTENING Part 3.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_10);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q7: Answer this MULTIPLE_CHOICE question for LISTENING Part 3.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_10);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'FILL_BLANK', 'BAND_5_6', 'Q8: Answer this FILL_BLANK question for LISTENING Part 3.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_10);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MATCHING', 'BAND_5_6', 'Q9: Answer this MATCHING question for LISTENING Part 3.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_10);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q10: Answer this MULTIPLE_CHOICE question for LISTENING Part 3.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_10);

-- LISTENING Part 4 for Real Test
INSERT INTO qb_question_groups (skill, title, content, difficulty_band, author_id, created_at) VALUES ('LISTENING', 'Real Test - LISTENING Part 4', 'Placeholder audio transcript for LISTENING part 4...', 'BAND_5_6', 5, NOW());
SET @group_11 = LAST_INSERT_ID();
INSERT INTO qb_exam_groups (exam_id, group_id) VALUES (@real_exam, @group_11);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q1: Answer this MULTIPLE_CHOICE question for LISTENING Part 4.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_11);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'FILL_BLANK', 'BAND_5_6', 'Q2: Answer this FILL_BLANK question for LISTENING Part 4.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_11);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MATCHING', 'BAND_5_6', 'Q3: Answer this MATCHING question for LISTENING Part 4.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_11);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q4: Answer this MULTIPLE_CHOICE question for LISTENING Part 4.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_11);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'FILL_BLANK', 'BAND_5_6', 'Q5: Answer this FILL_BLANK question for LISTENING Part 4.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_11);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MATCHING', 'BAND_5_6', 'Q6: Answer this MATCHING question for LISTENING Part 4.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_11);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q7: Answer this MULTIPLE_CHOICE question for LISTENING Part 4.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_11);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'FILL_BLANK', 'BAND_5_6', 'Q8: Answer this FILL_BLANK question for LISTENING Part 4.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_11);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MATCHING', 'BAND_5_6', 'Q9: Answer this MATCHING question for LISTENING Part 4.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_11);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('LISTENING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q10: Answer this MULTIPLE_CHOICE question for LISTENING Part 4.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_11);

-- READING Part 1 for Real Test
INSERT INTO qb_question_groups (skill, title, content, difficulty_band, author_id, created_at) VALUES ('READING', 'Real Test - READING Part 1', 'Placeholder content for READING passage 1...', 'BAND_5_6', 5, NOW());
SET @group_12 = LAST_INSERT_ID();
INSERT INTO qb_exam_groups (exam_id, group_id) VALUES (@real_exam, @group_12);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q1: Answer this MULTIPLE_CHOICE question for READING Part 1.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_12);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'FILL_BLANK', 'BAND_5_6', 'Q2: Answer this FILL_BLANK question for READING Part 1.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_12);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MATCHING', 'BAND_5_6', 'Q3: Answer this MATCHING question for READING Part 1.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_12);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q4: Answer this MULTIPLE_CHOICE question for READING Part 1.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_12);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'FILL_BLANK', 'BAND_5_6', 'Q5: Answer this FILL_BLANK question for READING Part 1.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_12);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MATCHING', 'BAND_5_6', 'Q6: Answer this MATCHING question for READING Part 1.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_12);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q7: Answer this MULTIPLE_CHOICE question for READING Part 1.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_12);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'FILL_BLANK', 'BAND_5_6', 'Q8: Answer this FILL_BLANK question for READING Part 1.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_12);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MATCHING', 'BAND_5_6', 'Q9: Answer this MATCHING question for READING Part 1.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_12);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q10: Answer this MULTIPLE_CHOICE question for READING Part 1.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_12);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'FILL_BLANK', 'BAND_5_6', 'Q11: Answer this FILL_BLANK question for READING Part 1.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_12);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MATCHING', 'BAND_5_6', 'Q12: Answer this MATCHING question for READING Part 1.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_12);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q13: Answer this MULTIPLE_CHOICE question for READING Part 1.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_12);

-- READING Part 2 for Real Test
INSERT INTO qb_question_groups (skill, title, content, difficulty_band, author_id, created_at) VALUES ('READING', 'Real Test - READING Part 2', 'Placeholder content for READING passage 2...', 'BAND_5_6', 5, NOW());
SET @group_13 = LAST_INSERT_ID();
INSERT INTO qb_exam_groups (exam_id, group_id) VALUES (@real_exam, @group_13);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q1: Answer this MULTIPLE_CHOICE question for READING Part 2.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_13);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'FILL_BLANK', 'BAND_5_6', 'Q2: Answer this FILL_BLANK question for READING Part 2.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_13);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MATCHING', 'BAND_5_6', 'Q3: Answer this MATCHING question for READING Part 2.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_13);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q4: Answer this MULTIPLE_CHOICE question for READING Part 2.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_13);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'FILL_BLANK', 'BAND_5_6', 'Q5: Answer this FILL_BLANK question for READING Part 2.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_13);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MATCHING', 'BAND_5_6', 'Q6: Answer this MATCHING question for READING Part 2.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_13);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q7: Answer this MULTIPLE_CHOICE question for READING Part 2.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_13);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'FILL_BLANK', 'BAND_5_6', 'Q8: Answer this FILL_BLANK question for READING Part 2.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_13);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MATCHING', 'BAND_5_6', 'Q9: Answer this MATCHING question for READING Part 2.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_13);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q10: Answer this MULTIPLE_CHOICE question for READING Part 2.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_13);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'FILL_BLANK', 'BAND_5_6', 'Q11: Answer this FILL_BLANK question for READING Part 2.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_13);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MATCHING', 'BAND_5_6', 'Q12: Answer this MATCHING question for READING Part 2.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_13);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q13: Answer this MULTIPLE_CHOICE question for READING Part 2.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_13);

-- READING Part 3 for Real Test
INSERT INTO qb_question_groups (skill, title, content, difficulty_band, author_id, created_at) VALUES ('READING', 'Real Test - READING Part 3', 'Placeholder content for READING passage 3...', 'BAND_5_6', 5, NOW());
SET @group_14 = LAST_INSERT_ID();
INSERT INTO qb_exam_groups (exam_id, group_id) VALUES (@real_exam, @group_14);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q1: Answer this MULTIPLE_CHOICE question for READING Part 3.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_14);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'FILL_BLANK', 'BAND_5_6', 'Q2: Answer this FILL_BLANK question for READING Part 3.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_14);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MATCHING', 'BAND_5_6', 'Q3: Answer this MATCHING question for READING Part 3.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_14);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q4: Answer this MULTIPLE_CHOICE question for READING Part 3.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_14);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'FILL_BLANK', 'BAND_5_6', 'Q5: Answer this FILL_BLANK question for READING Part 3.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_14);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MATCHING', 'BAND_5_6', 'Q6: Answer this MATCHING question for READING Part 3.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_14);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q7: Answer this MULTIPLE_CHOICE question for READING Part 3.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_14);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'FILL_BLANK', 'BAND_5_6', 'Q8: Answer this FILL_BLANK question for READING Part 3.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_14);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MATCHING', 'BAND_5_6', 'Q9: Answer this MATCHING question for READING Part 3.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_14);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q10: Answer this MULTIPLE_CHOICE question for READING Part 3.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_14);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'FILL_BLANK', 'BAND_5_6', 'Q11: Answer this FILL_BLANK question for READING Part 3.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_14);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MATCHING', 'BAND_5_6', 'Q12: Answer this MATCHING question for READING Part 3.', '{"left_items":[{"id":"1","text":"Item 1"},{"id":"2","text":"Item 2"}],"right_items":[{"id":"A","text":"Match A"},{"id":"B","text":"Match B"},{"id":"C","text":"Match C"}],"solution":{"1":"B","2":"A"}}', false, 5, @group_14);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'MULTIPLE_CHOICE', 'BAND_5_6', 'Q13: Answer this MULTIPLE_CHOICE question for READING Part 3.', '{"options":[{"id":"a","label":"Option A"},{"id":"b","label":"Option B"},{"id":"c","label":"Option C"},{"id":"d","label":"Option D"}],"correct_ids":["b"],"multiple_select":false}', false, 5, @group_14);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id, group_id) VALUES ('READING', 'FILL_BLANK', 'BAND_5_6', 'Q14: Answer this FILL_BLANK question for READING Part 3.', '{"template":"The [blank1] brown fox jumps over the lazy [blank2].","blanks":{"[blank1]":{"correct":["quick","fast"],"max_words":1},"[blank2]":{"correct":["dog","canine"],"max_words":1}},"answer_pool":["cat","slow","mouse"]}', false, 5, @group_14);

-- Writing Tasks for Real Test
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id) VALUES ('WRITING', 'ESSAY', 'BAND_5_6', 'Writing Task 1 for Real Test: Discuss...', '{}', false, 5);
SET @writing_RealTest_1 = LAST_INSERT_ID();
INSERT INTO qb_exam_questions (exam_id, question_id) VALUES (@real_exam, @writing_RealTest_1);
INSERT INTO qb_questions (skill, type, difficulty_band, instruction, data, is_premium_content, author_id) VALUES ('WRITING', 'ESSAY', 'BAND_5_6', 'Writing Task 2 for Real Test: Discuss...', '{}', false, 5);
SET @writing_RealTest_2 = LAST_INSERT_ID();
INSERT INTO qb_exam_questions (exam_id, question_id) VALUES (@real_exam, @writing_RealTest_2);

SET FOREIGN_KEY_CHECKS=1;
